// test/shots.mjs — 画面の見た目を確かめるためのスクリーンショットを撮る (test/shot-*.png)
import { chromium } from 'playwright';
const FILES = new URL('./demo/', import.meta.url).pathname;
const b = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
p.on('pageerror', (e) => console.log('PAGEERR', String(e)));
await p.goto('http://localhost:8770/?open=' + encodeURIComponent(FILES + 'demo.jpg'));
await p.waitForFunction(() => window.__iv && __iv.S.bmp);
await p.evaluate(() => { localStorage.clear(); __iv.togglePanel(false); });
await p.waitForTimeout(300);
await p.screenshot({ path: 'test/shot-1-view.png' });
await p.keyboard.press('c');
await p.selectOption('#crop-aspect', '16:9');
await p.waitForTimeout(300);
await p.screenshot({ path: 'test/shot-2-crop.png' });
await p.keyboard.press('Enter');
await p.keyboard.press('m');
const scr = (x, y) => p.evaluate(([x, y]) => { const r = document.getElementById('view').getBoundingClientRect(), s = __iv.view.toScreen(x, y); return [r.left + s.x, r.top + s.y]; }, [x, y]);
const drag = async (a, c) => { const s = await scr(...a), e = await scr(...c); await p.mouse.move(s[0], s[1]); await p.mouse.down(); await p.mouse.move(e[0], e[1], { steps: 5 }); await p.mouse.up(); };
const cr = await p.evaluate(() => __iv.S.edit.crop);
await drag([500 - cr.x, 380 - cr.y], [1100 - cr.x, 470 - cr.y]);
await p.evaluate(() => { for (const [k, v] of [['brightness', 15], ['contrast', 20], ['saturation', 25]]) { const s = document.getElementById('adj-' + k); s.value = v; s.dispatchEvent(new Event('input')); s.dispatchEvent(new Event('change')); } __iv.setResize('width', 1280); });
await p.waitForTimeout(900);
await p.screenshot({ path: 'test/shot-3-edit.png' });
await p.keyboard.press('Escape');
await p.evaluate(() => document.getElementById('panel').scrollTo(0, 9999));
await p.waitForTimeout(300);
await p.screenshot({ path: 'test/shot-4-export.png' });
await p.keyboard.press('F1');
await p.waitForTimeout(200);
await p.screenshot({ path: 'test/shot-5-help.png' });
await p.keyboard.press('Escape');
await p.click('button[data-act="presetEdit"]');
await p.waitForTimeout(200);
await p.screenshot({ path: 'test/shot-6-presets.png' });
await b.close();
